# Generated by Django 2.2.16 on 2020-11-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20201108_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='image/%Y%m', verbose_name='封面图'),
        ),
    ]
